---

- hosts: all
  become: true
  tasks:

  - name: update repository index 
    apt:
     update_cache: yes
        
  - name: install docker package
    apt:
       name: docker.io
       state: latest
  - name: install docker-compose package
    apt:
       name: docker-compose
       state: latest
  - name: install git package
    apt:
       name: git
       state: latest
